language: csharp
solution: WealthFarm.SparkPost.sln
dotnet: 1.0.4
install:
  - nuget restore WealthFarm.SparkPost.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  - dotnet restore
script:
  - msbuild /p:Configuration=Release WealthFarm.SparkPost.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/WealthFarm.SparkPost.Tests/bin/Release/netcoreapp1.0/WealthFarm.SparkPost.Tests.dll
  - dotnet pack --include-symbols -c Release
deploy:
  skip_cleanup: true
