language: csharp
solution: WealthFarm.SparkPost.sln
dotnet: 1.0.4
install:
  - nuget restore WealthFarm.SparkPost.sln
  - dotnet restore
script:
  - msbuild /p:Configuration=Release WealthFarm.SparkPost.sln
  - dotnet pack --include-symbols -c Release
